# LOGGING (Spring Boot 2 requires logging.file.name)
logging:
  file:
    name: /home/lylio/Documents/logs/emergency-contacts.log

# BANNER
spring.banner.location: classpath:banner.txt

# ENDPOINT MANAGEMENT
management:
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"